[package]
name = "calculator"
version = "0.1.0"
authors = ["Prodige <prodigetukala@hotmail.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
